package com.saiferwp.currencyexchange.utils

import android.text.InputFilter
import android.text.Spanned
import com.saiferwp.currencyexchange.DECIMAL_PLACES_FOR_ROUNDING
import com.saiferwp.currencyexchange.MAX_DIGITS_BEFORE_DECIMAL

// generated by Gemini
class MoneyAmountInputFilter : InputFilter {

    override fun filter(
        source: CharSequence,
        start: Int,
        end: Int,
        dest: Spanned,
        dstart: Int,
        dend: Int
    ): CharSequence? {
        val builder = StringBuilder(dest)
        builder.replace(dstart, dend, source.subSequence(start, end).toString())
        val newString = builder.toString()

        if (newString.isEmpty()) {
            return null // Allow empty input
        }

        if (!newString.matches(Regex("^[0-9]{0,$MAX_DIGITS_BEFORE_DECIMAL}(\\.[0-9]{0,$DECIMAL_PLACES_FOR_ROUNDING})?$"))) {
            return "" // Invalid input, reject
        }

        return null // Accept input
    }
}