package com.saiferwp.currencyexchange.utils

import android.text.InputFilter
import android.text.Spanned

// generated by Gemini
class MoneyAmountInputFilter : InputFilter {

    private val maxDigitsBeforeDecimal = 10
    private val maxDigitsAfterDecimal = 2

    override fun filter(
        source: CharSequence,
        start: Int,
        end: Int,
        dest: Spanned,
        dstart: Int,
        dend: Int
    ): CharSequence? {
        val builder = StringBuilder(dest)
        builder.replace(dstart, dend, source.subSequence(start, end).toString())
        val newString = builder.toString()

        if (newString.isEmpty()) {
            return null // Allow empty input
        }

        if (!newString.matches(Regex("^[0-9]{0,$maxDigitsBeforeDecimal}(\\.[0-9]{0,$maxDigitsAfterDecimal})?$"))) {
            return "" // Invalid input, reject
        }

        return null // Accept input
    }
}